use splunkdb;

CREATE TABLE splunkers
(
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
name TEXT,
PRIMARY KEY (id)
) COMMENT='this is my Splunkers list';

INSERT INTO splunkers(name) VALUES("Buttercup");